<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CompleteFileExt */

$this->title = $model->reg_id;
$this->params['breadcrumbs'][] = ['label' => 'Complete File Exts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>

<div class="container-fluid">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12">
                    <p>
                        <?= Html::a('Update', ['update', 'id' => $model->reg_id], ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Delete', ['delete', 'id' => $model->reg_id], [
                            'class' => 'btn btn-danger',
                            'data' => [
                                'confirm' => 'Are you sure you want to delete this item?',
                                'method' => 'post',
                            ],
                        ]) ?>
                    </p>
                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'reg_id',
                            'staff_id',
                            'date_receive_file',
                            'date_start_ri',
                            'date_end_ri',
                            'r_j',
                            'r_k',
                            'r_l',
                            'r_m',
                            'r_n',
                            'r_o',
                            'r_p',
                            'r_q',
                            'r_r',
                            'r_s',
                            'r_t',
                            'r_u',
                            'r_v',
                            'r_w',
                            'r_x',
                            'r_y',
                            'r_z',
                            'r_aa',
                            'r_ab',
                            'r_ac',
                            'r_ad',
                            'r_ae',
                            'r_af',
                            'r_ag',
                            'r_ah',
                            'r_ai',
                            'r_aj',
                            'r_ak',
                            'r_al',
                            'r_am',
                            'o_i',
                            'o_j',
                            'o_k',
                            'o_l',
                            'o_m',
                            'o_n',
                            'o_o',
                            'o_p',
                            'o_q',
                            'o_r',
                            'o_s',
                            'o_t',
                            'o_u',
                            'o_v',
                            'o_w',
                            'o_x',
                            'o_y',
                            'o_z',
                            'o_aa',
                            'o_ab',
                            'o_ac',
                            'o_ad',
                            'o_ae',
                            'o_af',
                            'a_i',
                            'a_j',
                            'a_k',
                            'a_l',
                            'a_m',
                            'a_n',
                            'a_o',
                            'a_p',
                            'a_q',
                            'a_r',
                            'a_s',
                            'a_t',
                            'a_u',
                            'a_v',
                            'a_w',
                            'a_x',
                            'a_y',
                            'a_z',
                            'a_aa',
                            'a_ab',
                            'a_ac',
                            'a_ad',
                            'a_ae',
                            'a_af',
                            'a_ag',
                            'a_ah',
                            'a_ai',
                            'a_aj',
                            'a_ak',
                            'a_al',
                            'a_am',
                            'a_an',
                            'a_ao',
                            'a_ap',
                            'a_aq',
                            'a_ar',
                            'i_i',
                            'i_j',
                            'i_k',
                            'i_l',
                            'i_m',
                            'i_n',
                            'i_o',
                            'i_p',
                            'i_q',
                            'i_r',
                            'i_s',
                            'i_t',
                            'i_u',
                            'i_v',
                            'i_w',
                            'i_x',
                            'i_y',
                            'i_z',
                            'i_aa',
                            'i_ab',
                            'i_ac',
                            'i_ad',
                            'i_ae',
                            'i_af',
                            'i_ag',
                            'i_ah',
                            'i_ai',
                            'i_aj',
                            'i_ak',
                            't_j',
                            't_k',
                            't_l',
                            't_m',
                            't_n',
                            't_o',
                            't_p',
                            't_q',
                            't_r',
                            't_s',
                            't_t',
                            't_u',
                            't_v',
                            't_w',
                            't_x',
                            't_y',
                            't_z',
                            't_aa',
                            't_ab',
                            't_ac',
                            't_ad',
                            't_ae',
                            't_af',
                            't_ag',
                            't_ah',
                            't_ai',
                            't_aj',
                            't_ak',
                            't_al',
                            'aa_j',
                            'aa_k',
                            'aa_l',
                            'aa_m',
                            'aa_n',
                            'aa_o',
                            'aa_p',
                            'aa_q',
                            'aa_r',
                            'aa_s',
                            'aa_t',
                            'aa_u',
                            'aa_v',
                            'aa_w',
                            'aa_x',
                            'aa_y',
                            'aa_z',
                            'aa_aa',
                            'aa_ab',
                            'aa_ac',
                            'aa_ad',
                            'aa_ae',
                            'aa_af',
                            'aa_ag',
                            'aa_ah',
                            'aa_ai',
                            'aa_aj',
                            'aa_ak',
                            'aa_al',
                            'aa_am',
                            'aa_an',
                            'aa_ao',
                            'aa_ap',
                            'aa_aq',
                            'aa_ar',
                            'r_cp',
                            'r_date_cp',
                            'o_cp',
                            'o_date_cp',
                            'a_cp',
                            'a_date_cp',
                            'i_cp',
                            'i_date_cp',
                            't_cp',
                            't_date_cp',
                            'aa_cp',
                            'aa_date_cp',
                            'created_user_id',
                            'created_time',
                        ],
                    ]) ?>
                </div>
                <!--.col-md-12-->
            </div>
            <!--.row-->
        </div>
        <!--.card-body-->
    </div>
    <!--.card-->
</div>